[colors.primary]
background = "#001127"
foreground = "#ffffff"

[colors.cursor]
text = "#001127"
cursor = "#ffffff"

[colors.vi_mode_cursor]
text = "#001127"
cursor = "#ffffff"

[colors.search.matches]
foreground = "#001127"
background = "#ffffff"

[colors.search.focused_match]
foreground = "#ffffff"
background = "#e0283c"

[colors.footer_bar]
foreground = "#ffffff"
background = "#0a2240"

[colors.selection]
text = "#ffffff"
background = "#1c3d66"

[colors.normal]
black = "#0a2240"
red = "#e0283c"
green = "#ffffff"
yellow = "#ffffff"
blue = "#ffffff"
magenta = "#ffffff"
cyan = "#ffffff"
white = "#ffffff"

[colors.bright]
black = "#3f6390"
red = "#ffffff"
green = "#ffffff"
yellow = "#ffffff"
blue = "#ffffff"
magenta = "#ffffff"
cyan = "#ffffff"
white = "#ffffff"

[window]
opacity = 0.75
