$activeBorderColor = rgba(e0283cee) rgba(6fc3dfee) 45deg
$inactiveBorderColor = rgba(1c3d66aa)

general {
    col.active_border = $activeBorderColor
    col.inactive_border = $inactiveBorderColor
}

group {
    col.border_active = $activeBorderColor
    col.border_inactive = $inactiveBorderColor
    groupbar {
        col.active = rgb(e0283c)
        col.inactive = rgb(1c3d66)
        text_color = rgb(ffffff)
    }
}
